# Generated by Django 4.0.2 on 2022-02-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
    ]
